vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        categorie_image:
            uri_prefix: /uploads/categories
            upload_destination: '%kernel.project_dir%/public/uploads/categorie'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        projets:
            uri_prefix: /uploads/projets
            upload_destination: '%kernel.project_dir%/public/uploads/projets'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

